### ISSUE TITLE
Analytics > Duplicate Metabase KPI Dashboard for AUS

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/product-pipe#10]
To facilitate / speed up the community feedback process on the first version of a KPI Dashboard the version built for OFN France needs to be duplicated for OFN AUS.

Link to Discourse Post about the Global KPI Project:
https://community.openfoodnetwork.org/t/analytics-metabase-kpi-dashboard/2116/8

**Comment by jaycmb** [comment]
Link to the Dashboard: https://data.openfoodnetwork.org.uk/dashboard/25

Feedback welcome @kirstenalarsen :)

**Comment by kirstenalarsen** [comment]
this is SO AWESOME! Thank you @jaycmb - you can ignore or incorporate any feedback from below. These are just the things that came to mind at my first glance. I would really love to hear from aus customer support team and will ping them more :)

**Sales  & Orders KPIs**
* I am confused about the 'Sum of Total Platform Sales' vs the 'Sum of Total Payments'. I have the month of October selected, sales is $379,280 and payments is $4,267,795 - something seems wrong here?
* I can't work out how to open /zom the Development ot Total # of Orders  & Avg Order Size - this is REALLY cool by the way!

**User KPIs / Enterprise**
* '# of enterprises (total) - immediate question for me was producers / hubs
I realise this is lower down in the # of enterprises, split by 'sells' - but I think that one is totals rather than new? or is it active
-> perhaps change the first  '# of enterprises' to '# of enterprise sign-ups' and display it with the breakdown by 'sells' - would be really useful
* same for the bar chart with # of New Enterprises - if this could be shown as a stacked bar broken up by Sells that would be amazing, but I realise that might be stretching metabase!
* I'm not sure that # of non-distributors is that useful. I think a metric like '# of distributors signed up in last x months that never distributed an order' would be useful, because it becomes a metric around successful on-boarding. 
* I would actually like to see % of 'sells own or any' enterprises that have signed up in X months that HAVE had a sale - getting ambitious here :)
* Perhaps rename 'Distributors' as 'Shops' because that's what we mean - are trading, Distribuors is in the code but it isn't really what we call them from customer service perspective 
* Same with visibility - total visibility isn't that useful because we know that many many of these are obsolete. What might be more useful is some combo of:
 - number of visible enterprises
 - proportion of total enterprises visible (%) 
 - '# / % of new enterprises this month/last month that are visible i.e. are people making it through sign-up to a public profile or getting stuck

These suggestions would give us more immediate feedback on our on-boarding etc

**User KPIs / Shopper**
Perhaps just rename Shopper or Customers (enterprises are also users)
* '# of Shoppers perhaps renamed to new? When I have any date filters selected it is new. With no filters is only time it is 'all', so perhaps # of (new) confirmed Shoppers (then i don't need to read the tooltip)
* is # of Customers unique customers? or total orders? i think the former because we have orders in the first block. Perhaps just call it # of Unique Customers?
* Perhaps # of Customers with more than one order would be useful, or donut diagram showing number of customers with 1, 2, 3 ,4 orders etc?
* '# of inactive shoppers - this is everyone with confirmed email but no orders, AND no enterprise? If so we don't really know if they are failed enterprises or failed shoppers. Not sure if we should rename to make that clearer

**Comment by jaycmb** [comment]
Sales & Orders KPIs

>  I am confused about the 'Sum of Total Platform Sales' vs the 'Sum of Total Payments'. I have the month of October selected, sales is $379,280 and payments is $4,267,795 - something seems wrong here?

-> Indeed, the filter was not working on payments, so it kept on showing aggregation of all time payments.  Solved now.

> I can't work out how to open /zom the Development ot Total # of Orders & Avg Order Size - this is REALLY cool by the way!

That´s so weird. On the France dashboard that works perfectly. https://data.openfoodnetwork.org.uk/question/173. I don´t know what´s the issue.

> '# of enterprises (total) - immediate question for me was producers / hubs
I realise this is lower down in the # of enterprises, split by 'sells' - but I think that one is totals rather than new? or is it active
-> perhaps change the first '# of enterprises' to '# of enterprise sign-ups' and display it with the breakdown by 'sells' - would be really useful

->  Yes, Total Number of Enterprises is just summarizing, whereas "# of New Enterprises shows this same metric over time. Moving up the "Enterprises by Sells" then

> I'm not sure that # of non-distributors is that useful. I think a metric like '# of distributors signed up in last x months that never distributed an order' would be useful, because it becomes a metric around successful on-boarding. 

True. Not sure if we can get this correctly, because there is some confusion around the definition of an active shop: is it an enterprise that has sells "any" or sells "own" - or is it an enterprise with _Order ID not empty?_ @sauloperez to please doublecheck this attempt of visualizing Number of Enterprises that signed up per month and did not have an order (yet)
https://data.openfoodnetwork.org.uk/question/212

> I would actually like to see % of 'sells own or any' enterprises that have signed up in X months that HAVE had a sale - getting ambitious here :)

Yeah, unfortuately %/shares is not possible with Metabase visualization.
But I **think** this would be possible in that direction: Shops that signed up that month and had a sale the same month:
https://data.openfoodnetwork.org.uk/question/213 
@sauloperez is this correct?

**User KPIs Shoppers**

- [x] Updated # of **New Confirmed** Shoppers and #of **Unique** Customers


> Perhaps # of Customers with more than one order would be useful, or donut diagram showing number of customers with 1, 2, 3 ,4 orders etc?

For sure. This is next step, when about  analyzing purchasing frequency (and sales frequency of shops) and creating user segments (one-timer vs regular shoppers etc).
These queries are more complex, issue created here:
https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/inception-pipe/23 


> '# of inactive shoppers - this is everyone with confirmed email but no orders, AND no enterprise? If so we don't really know if they are failed enterprises or failed shoppers. Not sure if we should rename to make that clearer

Oh true, I I remember we had some discussion with @sauloperez how to define inactive shopper and not sure if this query currently is correct because would include enterprise users that did not place an order.
https://data.openfoodnetwork.org.uk/question/205
